name: tests

on:
  push:
  pull_request:
    types:
      - synchronize

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Merge PR if tests pass
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'synchronize' && success() }}
        run:
          git fetch origin pull/${{ github.event.pull_request.number }}/merge --no-tags --update-head-ok
          git merge FETCH_HEAD --no-ff --no-commit
          git commit -m "Automatically merged PR"
          git push origin HEAD:refs/heads/main
